# Python fundamental data types

### These are fundamental data types in Python

In [1]:
a = 2 # ---> variable

In [2]:
b = [2,3,'blah', 45] # --> list

In [3]:
c = {'voltage0':3, 'max_current': 40} # --> dictionary

In [4]:
d = {3,4,5,6} # --> set

In [5]:
e = (2,3) # ---> tuple

From these, the first three (i.e. variables, lists and dictionaries are used a lot)

### Not so fundamental data type, but heavily used

There is another very famous type which is similar to Lists, but ONLY allows numbers. It is called NDARRAY --> which means n-dimensional array.

The only differece is that it is not fundamental so it needs a library import:

In [6]:
import numpy as np

In [7]:
f = np.array([5,6,7,4,56,7]) # ---> ndarray
f

array([ 5,  6,  7,  4, 56,  7])

### Playing with data types

In [8]:
# Lists can contain a lot of things

g = [2,3,4,8,55, 'sahil', 'cousar', 'caroline']

In [9]:
# You can iterate through any list like object

for some_element in a:
    print(some_element)

TypeError: 'int' object is not iterable

In [ ]:
# Another example of List like object

for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [ ]:
h = np.random.randint(20, size=20)
h

array([19,  2,  4,  7,  7,  7,  9, 10, 11,  8,  3, 17, 11,  9,  5,  3, 16,
       13,  2, 14])

In [ ]:
np.reshape(h, (4,5))

array([[19,  2,  4,  7,  7],
       [ 7,  9, 10, 11,  8],
       [ 3, 17, 11,  9,  5],
       [ 3, 16, 13,  2, 14]])

In [ ]:
for whateveryouliketocallit in b:
    print(f'Hello my friend: {whateveryouliketocallit ** 2}')

Hello my friend: 361
Hello my friend: 4
Hello my friend: 16
Hello my friend: 49
Hello my friend: 49
Hello my friend: 49
Hello my friend: 81
Hello my friend: 100
Hello my friend: 121
Hello my friend: 64
Hello my friend: 9
Hello my friend: 289
Hello my friend: 121
Hello my friend: 81
Hello my friend: 25
Hello my friend: 9
Hello my friend: 256
Hello my friend: 169
Hello my friend: 4
Hello my friend: 196


In [ ]:
# Playing with the dictionary

print(c['voltage0'])

3


In [ ]:
print(c['max_current'])

40
