# Python fundamental data types

### These are fundamental data types in Python

In [1]:
a=2 # ---> variable

In [2]:
a=[2,3,'blah', 45] # --> list

In [3]:
a = {'voltage0':3, 'max_current': 40} # --> dictionary

In [4]:
a={3,4,5,6} # --> set

In [5]:
a=(2,3) # ---> tuple

From these, the first three (i.e. variables, lists and dictionaries are used a lot)

### Not so fundamental data type, but heavily used

There is another very famous type which is similar to Lists, but ONLY allows numbers. The only differece is that it is not fundamental so it needs a library import:

In [6]:
import numpy as np

In [7]:
a = np.array([5,6,7,4,56,7])
a

array([ 5,  6,  7,  4, 56,  7])

### Playing with data types

In [8]:
# Lists can contain a lot of things

a = [2,3,4,8,55, 'sahil', 'cousar', 'caroline']

In [9]:
# You can iterate through any list like object

for some_element in a:
    print(some_element)

2
3
4
8
55
sahil
cousar
caroline


In [10]:
# Another example of List like object

for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [11]:
b = np.random.randint(20, size=20)
b

array([ 1,  0, 14,  6, 13, 19,  5,  4, 10,  2,  6, 12, 18,  5,  6, 19,  1,
        5, 10, 17])

In [12]:
np.reshape(b, (4,5))

array([[ 1,  0, 14,  6, 13],
       [19,  5,  4, 10,  2],
       [ 6, 12, 18,  5,  6],
       [19,  1,  5, 10, 17]])

In [13]:
for whateveryouliketocallit in b:
    print(f'Hello my friend: {whateveryouliketocallit ** 2}')

Hello my friend: 1
Hello my friend: 0
Hello my friend: 196
Hello my friend: 36
Hello my friend: 169
Hello my friend: 361
Hello my friend: 25
Hello my friend: 16
Hello my friend: 100
Hello my friend: 4
Hello my friend: 36
Hello my friend: 144
Hello my friend: 324
Hello my friend: 25
Hello my friend: 36
Hello my friend: 361
Hello my friend: 1
Hello my friend: 25
Hello my friend: 100
Hello my friend: 289
