# Applications of Accelerators 2023/2024

## Ex01

Q1- [1 point] Write in your own words, which force is most suitable for particle acceleration and why?

<font color='blue'>Electromagnetic force and the gravitational force have the proper range compared to the weak and strong forces. But between the electromagnetic and gravitational force, only the former has significant relative strength, that means it is basically the only possible choice for acceleration. This latter point then restricts us to choose charged particles only for acceleration. Among the available charaged particles with significant life time, again the choice is limited to electrons and ions (including the proton).</font>

Q2- [1 point] Calculate the force acted on a neutron that travels at the speed of 0.4c, affected only by a magnetic field of 1.5 [T].

<font color='blue'>Neutron is not a charged particle, so F = 0 ---> a neutron goes to a bar, asks how much for a beer, the barman says: for you no charge! :-)</font>

Q3- [1 point] Identify the heaviest of the leptons and the heaviest of the quarks and find out their mass by looking up in table / internet and write it here with units. 

<font color='blue'>Heaviest Lepton is tauon --> mass 1.7 GeV/c^2
Heaviest quark is Top Quark --> mass 172 GeV/c^2</font>

Q4- [1 point] Give a rough estimate how much heavier is a proton compared to an electron?

<font color='blue'>2000 times</font>

Q5- [1 point] Write *very short* definitions and classify the following concepts in groups:

Fermions
Bosons
Mesons
Hadrons
Baryons
Leptons

<font color='blue'>
- Fermions: particles with spin of multiple of 1/2
- Bosons: particles with integer spin
- Mesons: systems of 2 quarks
- Baryons: systems of 3 quarks
- Leptons: elementary fermions that do not get affected by strong interaction

leptons, baryons and fermions but mesons are bosons
</font>

Q6- [1 point] Which one of the elementary fermions is usually accelerated in an accelerator?

<font color='blue'>electron</font>

Q7- [1 point] Up and down quarks have a mass of the order 5 [$MeV/c^2$]. Why then is proton so heavy?

<font color='blue'>Proton has 3 quarks, that would be about 15 MeV/c^2, but its total mass is much more, that is 938 MeV/c^2. The rest of the mass is the result of strong binding energy of the gluons. Click [here](https://www.forbes.com/sites/startswithabang/2016/08/03/where-does-the-mass-of-a-proton-come-from/?sh=16486e082e1d) for more info.</font>

Q8- [1 point] Identify the coolest lepton! (spoiler: it is the muon). What is its mean life time and why do we detect atmospheric muons in the lab?

<font color='blue'>muons have a mean lifetime of 2.2us. Please [look here](http://hyperphysics.phy-astr.gsu.edu/hbase/Relativ/muon.html#c1) for more information.
</font>

Q9- [1 point] A linear accelerator can accelerate protons to 1.4 [TeV]. What is the available CoM energy if we shoot the protons on a fixed Beryllium target for an industrial application? What would be the available CoM energy if we use two such accelerators to form a collider?

In [11]:
import numpy as np
print (f'{np.sqrt(2*1400 * 0.938)} [GeV] vs. {2*1400} [GeV] !!!' )

51.24841460962475 [GeV] vs. 2800 [GeV] !!!


Q10- [1 point] How much voltage is needed to accelerate an electron to an energy of 5e-4 [J]?

<font color='blue'>
Here is the formula:

$$U = \frac{E}{e}$$

</font>

In [12]:
from scipy.constants import e
U = 5e-4 / e
print('Required voltage is {0:.2e} [V]'.format(U))

Required voltage is 3.12e+15 [V]


Q11- [2 points] Warmup computational exersize:

    Create a GitHUB account.
    Write a function in Python code that multiples 2 (two) 3x3 Matrices (ndarray) and returns the result.
    Call this function using two randomly generated 3 by 3 matrices and print the results.
    Place your code in your GitHUB repository and submit the link in your exercise document. The code can also be in the form of a Jupiter-Notebook on your GitHUB account.

Hint: if you have no previous experience with python: it is easy!
Hint: if you don't have time to learn python: it doesn't take time!

In [13]:
def my_matrix_mult(A, B):
    return A*B

In [14]:
import numpy as np

In [15]:
A = np.random.randint(10, size = 4)
A

array([6, 2, 2, 0])

In [16]:
A = np.reshape(A, (2,2))
A

array([[6, 2],
       [2, 0]])

In [17]:
B = np.random.randint(10, size = 4)
B

array([2, 1, 1, 7])

In [18]:
B = np.reshape(B, (2,2))
B

array([[2, 1],
       [1, 7]])

In [19]:
my_matrix_mult(A, B)

array([[12,  2],
       [ 2,  0]])

<font color='blue'>You will get the element by element multiplication, which is not equl to matrix multiplication. But you can use numpy own command for matrix multiplication:</font>

In [20]:
np.matmul(A, B)

array([[14, 20],
       [ 4,  2]])